"use client";

import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_component/Header";
import Footer from "./_component/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CartContext } from "./_context/CartContext";
import { useState } from "react";


const inter = Outfit({ subsets: ["latin"] });

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {

  const [cart,setCart]=useState([] )
  


  return (
    <ClerkProvider>
     <CartContext.Provider value={{cart,setCart} } >
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <hr className="height-{2px} width:50% "/>
        {children}
        <Footer/>
        </body>
    </html>
    </CartContext.Provider> 
    </ClerkProvider>
  );
}
